services:
    devcontainer:
        image: mcr.microsoft.com/devcontainers/rust:bullseye
        command: sleep infinity
        volumes:
            - ..:/workspace:cached

    db:
        image: mongo:latest
        ports:
            - 27018:27017
        volumes:
            - mongodb_data:/data/db

    redis:
        image: redis:latest
        ports:
            - 6378:6379

    redisinsight:
        image: redis/redisinsight:latest
        ports:
            - 5548:5540
        volumes:
            - redisinsight:/data

volumes:
    mongodb_data:
    redisinsight:
