[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
axum = "0.8.4"
futures = "0.3"
mongodb = { version = "3.2"}
nanoid = "0.4"
serde = {version = "1.0", features = ["derive"]}
tokio = {version = "1.45", features = ["full"]}
